/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VraagbaakRouteImport } from './routes/vraagbaak'
import { Route as SmoelenboekRouteImport } from './routes/smoelenboek'
import { Route as SharepointRouteImport } from './routes/sharepoint'
import { Route as PartnerportalenRouteImport } from './routes/partnerportalen'
import { Route as NieuwsRouteImport } from './routes/nieuws'
import { Route as KennisbankRouteImport } from './routes/kennisbank'
import { Route as InstellingenRouteImport } from './routes/instellingen'
import { Route as FinanceWikiRouteImport } from './routes/finance-wiki'
import { Route as DocumentenRouteImport } from './routes/documenten'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ApplicatiesRouteImport } from './routes/applicaties'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SmoelenboekIdRouteImport } from './routes/smoelenboek.$id'
import { Route as KennisbankSlugRouteImport } from './routes/kennisbank.$slug'
import { Route as FinanceWikiSlugRouteImport } from './routes/finance-wiki.$slug'
import { Route as KennisbankSlugArticleSlugRouteImport } from './routes/kennisbank.$slug.$articleSlug'

const VraagbaakRoute = VraagbaakRouteImport.update({
  id: '/vraagbaak',
  path: '/vraagbaak',
  getParentRoute: () => rootRouteImport,
} as any)
const SmoelenboekRoute = SmoelenboekRouteImport.update({
  id: '/smoelenboek',
  path: '/smoelenboek',
  getParentRoute: () => rootRouteImport,
} as any)
const SharepointRoute = SharepointRouteImport.update({
  id: '/sharepoint',
  path: '/sharepoint',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerportalenRoute = PartnerportalenRouteImport.update({
  id: '/partnerportalen',
  path: '/partnerportalen',
  getParentRoute: () => rootRouteImport,
} as any)
const NieuwsRoute = NieuwsRouteImport.update({
  id: '/nieuws',
  path: '/nieuws',
  getParentRoute: () => rootRouteImport,
} as any)
const KennisbankRoute = KennisbankRouteImport.update({
  id: '/kennisbank',
  path: '/kennisbank',
  getParentRoute: () => rootRouteImport,
} as any)
const InstellingenRoute = InstellingenRouteImport.update({
  id: '/instellingen',
  path: '/instellingen',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceWikiRoute = FinanceWikiRouteImport.update({
  id: '/finance-wiki',
  path: '/finance-wiki',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentenRoute = DocumentenRouteImport.update({
  id: '/documenten',
  path: '/documenten',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplicatiesRoute = ApplicatiesRouteImport.update({
  id: '/applicaties',
  path: '/applicaties',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SmoelenboekIdRoute = SmoelenboekIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => SmoelenboekRoute,
} as any)
const KennisbankSlugRoute = KennisbankSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => KennisbankRoute,
} as any)
const FinanceWikiSlugRoute = FinanceWikiSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => FinanceWikiRoute,
} as any)
const KennisbankSlugArticleSlugRoute =
  KennisbankSlugArticleSlugRouteImport.update({
    id: '/$articleSlug',
    path: '/$articleSlug',
    getParentRoute: () => KennisbankSlugRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/applicaties': typeof ApplicatiesRoute
  '/auth': typeof AuthRoute
  '/documenten': typeof DocumentenRoute
  '/finance-wiki': typeof FinanceWikiRouteWithChildren
  '/instellingen': typeof InstellingenRoute
  '/kennisbank': typeof KennisbankRouteWithChildren
  '/nieuws': typeof NieuwsRoute
  '/partnerportalen': typeof PartnerportalenRoute
  '/sharepoint': typeof SharepointRoute
  '/smoelenboek': typeof SmoelenboekRouteWithChildren
  '/vraagbaak': typeof VraagbaakRoute
  '/finance-wiki/$slug': typeof FinanceWikiSlugRoute
  '/kennisbank/$slug': typeof KennisbankSlugRouteWithChildren
  '/smoelenboek/$id': typeof SmoelenboekIdRoute
  '/kennisbank/$slug/$articleSlug': typeof KennisbankSlugArticleSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/applicaties': typeof ApplicatiesRoute
  '/auth': typeof AuthRoute
  '/documenten': typeof DocumentenRoute
  '/finance-wiki': typeof FinanceWikiRouteWithChildren
  '/instellingen': typeof InstellingenRoute
  '/kennisbank': typeof KennisbankRouteWithChildren
  '/nieuws': typeof NieuwsRoute
  '/partnerportalen': typeof PartnerportalenRoute
  '/sharepoint': typeof SharepointRoute
  '/smoelenboek': typeof SmoelenboekRouteWithChildren
  '/vraagbaak': typeof VraagbaakRoute
  '/finance-wiki/$slug': typeof FinanceWikiSlugRoute
  '/kennisbank/$slug': typeof KennisbankSlugRouteWithChildren
  '/smoelenboek/$id': typeof SmoelenboekIdRoute
  '/kennisbank/$slug/$articleSlug': typeof KennisbankSlugArticleSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/applicaties': typeof ApplicatiesRoute
  '/auth': typeof AuthRoute
  '/documenten': typeof DocumentenRoute
  '/finance-wiki': typeof FinanceWikiRouteWithChildren
  '/instellingen': typeof InstellingenRoute
  '/kennisbank': typeof KennisbankRouteWithChildren
  '/nieuws': typeof NieuwsRoute
  '/partnerportalen': typeof PartnerportalenRoute
  '/sharepoint': typeof SharepointRoute
  '/smoelenboek': typeof SmoelenboekRouteWithChildren
  '/vraagbaak': typeof VraagbaakRoute
  '/finance-wiki/$slug': typeof FinanceWikiSlugRoute
  '/kennisbank/$slug': typeof KennisbankSlugRouteWithChildren
  '/smoelenboek/$id': typeof SmoelenboekIdRoute
  '/kennisbank/$slug/$articleSlug': typeof KennisbankSlugArticleSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/applicaties'
    | '/auth'
    | '/documenten'
    | '/finance-wiki'
    | '/instellingen'
    | '/kennisbank'
    | '/nieuws'
    | '/partnerportalen'
    | '/sharepoint'
    | '/smoelenboek'
    | '/vraagbaak'
    | '/finance-wiki/$slug'
    | '/kennisbank/$slug'
    | '/smoelenboek/$id'
    | '/kennisbank/$slug/$articleSlug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/applicaties'
    | '/auth'
    | '/documenten'
    | '/finance-wiki'
    | '/instellingen'
    | '/kennisbank'
    | '/nieuws'
    | '/partnerportalen'
    | '/sharepoint'
    | '/smoelenboek'
    | '/vraagbaak'
    | '/finance-wiki/$slug'
    | '/kennisbank/$slug'
    | '/smoelenboek/$id'
    | '/kennisbank/$slug/$articleSlug'
  id:
    | '__root__'
    | '/'
    | '/applicaties'
    | '/auth'
    | '/documenten'
    | '/finance-wiki'
    | '/instellingen'
    | '/kennisbank'
    | '/nieuws'
    | '/partnerportalen'
    | '/sharepoint'
    | '/smoelenboek'
    | '/vraagbaak'
    | '/finance-wiki/$slug'
    | '/kennisbank/$slug'
    | '/smoelenboek/$id'
    | '/kennisbank/$slug/$articleSlug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApplicatiesRoute: typeof ApplicatiesRoute
  AuthRoute: typeof AuthRoute
  DocumentenRoute: typeof DocumentenRoute
  FinanceWikiRoute: typeof FinanceWikiRouteWithChildren
  InstellingenRoute: typeof InstellingenRoute
  KennisbankRoute: typeof KennisbankRouteWithChildren
  NieuwsRoute: typeof NieuwsRoute
  PartnerportalenRoute: typeof PartnerportalenRoute
  SharepointRoute: typeof SharepointRoute
  SmoelenboekRoute: typeof SmoelenboekRouteWithChildren
  VraagbaakRoute: typeof VraagbaakRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vraagbaak': {
      id: '/vraagbaak'
      path: '/vraagbaak'
      fullPath: '/vraagbaak'
      preLoaderRoute: typeof VraagbaakRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/smoelenboek': {
      id: '/smoelenboek'
      path: '/smoelenboek'
      fullPath: '/smoelenboek'
      preLoaderRoute: typeof SmoelenboekRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sharepoint': {
      id: '/sharepoint'
      path: '/sharepoint'
      fullPath: '/sharepoint'
      preLoaderRoute: typeof SharepointRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partnerportalen': {
      id: '/partnerportalen'
      path: '/partnerportalen'
      fullPath: '/partnerportalen'
      preLoaderRoute: typeof PartnerportalenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nieuws': {
      id: '/nieuws'
      path: '/nieuws'
      fullPath: '/nieuws'
      preLoaderRoute: typeof NieuwsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kennisbank': {
      id: '/kennisbank'
      path: '/kennisbank'
      fullPath: '/kennisbank'
      preLoaderRoute: typeof KennisbankRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instellingen': {
      id: '/instellingen'
      path: '/instellingen'
      fullPath: '/instellingen'
      preLoaderRoute: typeof InstellingenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance-wiki': {
      id: '/finance-wiki'
      path: '/finance-wiki'
      fullPath: '/finance-wiki'
      preLoaderRoute: typeof FinanceWikiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documenten': {
      id: '/documenten'
      path: '/documenten'
      fullPath: '/documenten'
      preLoaderRoute: typeof DocumentenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/applicaties': {
      id: '/applicaties'
      path: '/applicaties'
      fullPath: '/applicaties'
      preLoaderRoute: typeof ApplicatiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/smoelenboek/$id': {
      id: '/smoelenboek/$id'
      path: '/$id'
      fullPath: '/smoelenboek/$id'
      preLoaderRoute: typeof SmoelenboekIdRouteImport
      parentRoute: typeof SmoelenboekRoute
    }
    '/kennisbank/$slug': {
      id: '/kennisbank/$slug'
      path: '/$slug'
      fullPath: '/kennisbank/$slug'
      preLoaderRoute: typeof KennisbankSlugRouteImport
      parentRoute: typeof KennisbankRoute
    }
    '/finance-wiki/$slug': {
      id: '/finance-wiki/$slug'
      path: '/$slug'
      fullPath: '/finance-wiki/$slug'
      preLoaderRoute: typeof FinanceWikiSlugRouteImport
      parentRoute: typeof FinanceWikiRoute
    }
    '/kennisbank/$slug/$articleSlug': {
      id: '/kennisbank/$slug/$articleSlug'
      path: '/$articleSlug'
      fullPath: '/kennisbank/$slug/$articleSlug'
      preLoaderRoute: typeof KennisbankSlugArticleSlugRouteImport
      parentRoute: typeof KennisbankSlugRoute
    }
  }
}

interface FinanceWikiRouteChildren {
  FinanceWikiSlugRoute: typeof FinanceWikiSlugRoute
}

const FinanceWikiRouteChildren: FinanceWikiRouteChildren = {
  FinanceWikiSlugRoute: FinanceWikiSlugRoute,
}

const FinanceWikiRouteWithChildren = FinanceWikiRoute._addFileChildren(
  FinanceWikiRouteChildren,
)

interface KennisbankSlugRouteChildren {
  KennisbankSlugArticleSlugRoute: typeof KennisbankSlugArticleSlugRoute
}

const KennisbankSlugRouteChildren: KennisbankSlugRouteChildren = {
  KennisbankSlugArticleSlugRoute: KennisbankSlugArticleSlugRoute,
}

const KennisbankSlugRouteWithChildren = KennisbankSlugRoute._addFileChildren(
  KennisbankSlugRouteChildren,
)

interface KennisbankRouteChildren {
  KennisbankSlugRoute: typeof KennisbankSlugRouteWithChildren
}

const KennisbankRouteChildren: KennisbankRouteChildren = {
  KennisbankSlugRoute: KennisbankSlugRouteWithChildren,
}

const KennisbankRouteWithChildren = KennisbankRoute._addFileChildren(
  KennisbankRouteChildren,
)

interface SmoelenboekRouteChildren {
  SmoelenboekIdRoute: typeof SmoelenboekIdRoute
}

const SmoelenboekRouteChildren: SmoelenboekRouteChildren = {
  SmoelenboekIdRoute: SmoelenboekIdRoute,
}

const SmoelenboekRouteWithChildren = SmoelenboekRoute._addFileChildren(
  SmoelenboekRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApplicatiesRoute: ApplicatiesRoute,
  AuthRoute: AuthRoute,
  DocumentenRoute: DocumentenRoute,
  FinanceWikiRoute: FinanceWikiRouteWithChildren,
  InstellingenRoute: InstellingenRoute,
  KennisbankRoute: KennisbankRouteWithChildren,
  NieuwsRoute: NieuwsRoute,
  PartnerportalenRoute: PartnerportalenRoute,
  SharepointRoute: SharepointRoute,
  SmoelenboekRoute: SmoelenboekRouteWithChildren,
  VraagbaakRoute: VraagbaakRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
